name: Run test

on: [push, pull_request]

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]
        phpunit-versions: [ 'latest' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: pcov

      - name: Install dependency
        run: |
          composer install

      - name: Run test
        run: |
          ./vendor/bin/phpunit
